[tool.pytest.ini_options]
pythonpath = "."
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_file = ".report/logs/pytest-logs.txt"

markers = ['smoke: description',
   'regression: description',
    'integration: description']
# for playwright
# for report: --alluredir=.report/allure-results
addopts = "--browser chromium --tracing=retain-on-failure --screenshot=only-on-failure --output='.report/other' "
